#Подготовка данных

In [149]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import ensemble

In [150]:
df = pd.DataFrame
df = pd.read_csv('../data/qsar/qsar_fish_toxicity_preprocessed.csv' )
del df['Unnamed: 0']
df

CIC0  SM1_Dz  GATS1i  MLOGP  ...  NdssC_3  NdssC_4  NdssC_5  NdssC_6
0    3.260   0.829   1.676  1.453  ...        0        0        0        0
1    2.189   0.580   0.863  1.348  ...        0        0        0        0
2    2.125   0.638   0.831  1.348  ...        0        0        0        0
3    3.027   0.331   1.472  1.807  ...        0        0        0        0
4    2.094   0.827   0.860  1.886  ...        0        0        0        0
..     ...     ...     ...    ...  ...      ...      ...      ...      ...
903  2.801   0.728   2.226  0.736  ...        0        0        0        0
904  3.652   0.872   0.867  3.983  ...        1        0        0        0
905  3.763   0.916   0.878  2.918  ...        0        0        0        1
906  2.831   1.393   1.077  0.906  ...        0        0        0        0
907  4.057   1.032   1.183  4.754  ...        1        0        0        0

[908 rows x 17 columns]

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   CIC0                   908 non-null    float64
 1   SM1_Dz                 908 non-null    float64
 2   GATS1i                 908 non-null    float64
 3   MLOGP                  908 non-null    float64
 4   Quantitative_response  908 non-null    float64
 5   NdsCH_0                908 non-null    int64  
 6   NdsCH_1                908 non-null    int64  
 7   NdsCH_2                908 non-null    int64  
 8   NdsCH_3                908 non-null    int64  
 9   NdsCH_4                908 non-null    int64  
 10  NdssC_0                908 non-null    int64  
 11  NdssC_1                908 non-null    int64  
 12  NdssC_2                908 non-null    int64  
 13  NdssC_3                908 non-null    int64  
 14  NdssC_4                908 non-null    int64  
 15  NdssC_

In [187]:
X = df.iloc[:, :3].join(df.iloc[:, 4]).values
y = df.iloc[:, 3].values
print(X)

[[3.26  0.829 1.676 3.77 ]
 [2.189 0.58  0.863 3.115]
 [2.125 0.638 0.831 3.531]
 ...
 [3.763 0.916 0.878 4.818]
 [2.831 1.393 1.077 5.317]
 [4.057 1.032 1.183 8.201]]


In [188]:
print(y)

[ 1.453  1.348  1.348  1.807  1.886  0.706  2.942  2.851  2.942  1.591
  1.769  1.591  1.769  1.859  0.981  0.143  1.199 -0.115  1.107  1.807
 -1.169  3.988  4.068  3.395  2.526  3.112  2.51   2.591 -0.937  1.748
  0.024  2.837 -0.521  2.242  1.06   2.813  5.089  3.562  2.066  3.492
  2.274  2.102  2.37   1.533  3.906  1.565  0.787  2.193  2.217  2.849
  2.642  2.642  3.795  2.296  2.942  3.21   1.859  3.478  2.127  2.127
  1.859  0.411  1.619  0.408  2.026  0.094  1.672  1.817  0.347  0.347
  0.202  0.094  0.202 -1.053  0.202  0.202  0.202 -1.053 -1.306 -0.386
  0.706  2.274  3.291  2.05   6.203  1.869  1.064 -1.96   1.492  0.479
  1.442  1.587  2.942  1.859  3.21   2.127  1.859  0.893  0.057  4.063
  3.045  2.608  0.846  2.876  1.195  1.05   1.506  0.846  2.248 -0.063
  0.846 -0.063  2.06   0.996  0.996  2.604  2.419  0.8    0.548 -0.534
 -0.786 -0.534 -0.128  0.8    0.156  0.408  0.156  3.291  1.795 -0.45
  2.849  1.795  3.516  2.604  1.209  1.064 -0.226 -0.081 -0.081  3.124
  0.468

In [189]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

X_train

array([[3.199, 0.56 , 2.033, 1.02 ],
       [2.092, 1.359, 2.273, 4.796],
       [2.834, 0.134, 1.237, 3.03 ],
       ...,
       [2.834, 0.134, 1.322, 2.413],
       [1.075, 1.161, 0.865, 5.386],
       [3.014, 0.56 , 1.781, 0.898]])

In [190]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 0.43330254, -0.19687992,  1.9100526 , -2.117293  ],
       [-1.02365827,  1.69580024,  2.52580889,  0.50288256],
       [-0.04708652, -1.2059935 , -0.13220579, -0.72254912],
       ...,
       [-0.04708652, -1.2059935 ,  0.08587457, -1.15068692],
       [-2.36216698,  1.22677562, -1.08662805,  0.91228499],
       [ 0.18981767, -0.19687992,  1.26350849, -2.20194909]])

#Композиции алгоритмов

In [191]:
from sklearn.model_selection import GridSearchCV

##Бэггинг

In [192]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor

In [193]:
clf = GridSearchCV(DecisionTreeRegressor(), {'max_depth': range(1,20,2)})
clf.fit(X_train, y_train)
clf.best_params_

{'max_depth': 5}

In [195]:
%%time
dtr = DecisionTreeRegressor(max_depth=5)
bgc = BaggingRegressor(dtr)

bagging_parameters = {'n_estimators' : range(10, 50, 10), 'max_features' : range(1,8,1)}
bagging = GridSearchCV(bgc, bagging_parameters)
bagging.fit(X_train, y_train)

CPU times: user 4.01 s, sys: 46.5 ms, total: 4.06 s
Wall time: 4.04 s


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: max_features must be in (0, n_features]

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: max_features must be in (0, n_features]

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: max_features must be in (0, n_features]

  FitFailedWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this t

In [196]:
bagging.best_params_

{'max_features': 4, 'n_estimators': 40}

In [197]:
y_pred = bagging.predict(X_test)

model_score = bagging.score(X_test,y_test)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.6388630919241027
Mean Squared Error     :  0.7897861795354706
Root Mean Squared Error:  0.8886991501827098
Mean Absolute Error    :  0.6422312387231779


##Бустинг

In [198]:
from sklearn.ensemble import GradientBoostingRegressor

In [199]:
%%time
gbc = GradientBoostingRegressor()
boosting_parameters = {'n_estimators' : range(5,20,5), 'max_depth' : range(1,8,1)}
boosting = GridSearchCV(gbc, boosting_parameters)
boosting.fit(X_train, y_train)

CPU times: user 1.33 s, sys: 9.01 ms, total: 1.34 s
Wall time: 1.35 s


In [200]:
boosting.best_params_

{'max_depth': 7, 'n_estimators': 15}

In [201]:
y_pred = boosting.predict(X_test)

model_score = boosting.score(X_test,y_test)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.6441597586522722
Mean Squared Error     :  0.7782026662307756
Root Mean Squared Error:  0.8821579599089812
Mean Absolute Error    :  0.6304328839474673


##Стекинг

In [202]:
from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

In [203]:
%%time
estimators = [('lreg', LinearRegression()),('Rid', Ridge())]
sr = StackingRegressor(estimators=estimators)
stacking = sr.fit(X_train, y_train)

CPU times: user 24.2 ms, sys: 100 µs, total: 24.3 ms
Wall time: 23.4 ms


In [204]:
y_pred = boosting.predict(X_test)

model_score = stacking.score(X_test,y_test)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

print("Model Score            : ", model_score)
print("Mean Squared Error     : ", mse)
print("Root Mean Squared Error: ", mse**(1/2))
print("Mean Absolute Error    : ", mae)

Model Score            :  0.6238116231827527
Mean Squared Error     :  0.7782026662307756
Root Mean Squared Error:  0.8821579599089812
Mean Absolute Error    :  0.6304328839474673


#Вывод

Все алгоритмы показали приблизительно одинаковые результаты, однако, наилучшую точность показал бустинг