# Подготовка данных

In [7]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn import ensemble

In [26]:
df = pd.DataFrame
df = pd.read_csv('../data/caesarian/caesarian_preprocessed.csv' )
del df['Unnamed: 0']
df.head()

Age  Heart_Problem  ...  Delivery_time_1  Delivery_time_2
0   22              0  ...                0                0
1   26              0  ...                0                0
2   26              0  ...                1                0
3   28              0  ...                0                0
4   22              0  ...                0                0

[5 rows x 13 columns]

In [27]:
df['Caesarian'].unique()

array([0, 1])

In [28]:
df1 = df[:]
del df1['Caesarian']

In [29]:
X = df1.iloc[:, :].values
y = df.iloc[:, 2].values
print(X)

[[22  0  1  0  0  0  0  0  1  1  0  0]
 [26  0  0  1  0  0  0  1  0  1  0  0]
 [26  0  0  1  0  0  0  1  0  0  1  0]
 [28  0  1  0  0  0  0  0  1  1  0  0]
 [22  0  0  1  0  0  0  1  0  1  0  0]
 [26  0  1  0  0  0  1  0  0  0  1  0]
 [27  0  0  1  0  0  0  1  0  1  0  0]
 [32  0  0  0  1  0  0  1  0  1  0  0]
 [28  0  0  1  0  0  0  1  0  1  0  0]
 [27  0  1  0  0  0  0  1  0  0  1  0]
 [36  0  1  0  0  0  0  1  0  1  0  0]
 [33  0  1  0  0  0  1  0  0  0  1  0]
 [23  0  1  0  0  0  0  1  0  0  1  0]
 [20  1  1  0  0  0  0  1  0  1  0  0]
 [29  1  1  0  0  0  1  0  0  0  0  1]
 [25  0  1  0  0  0  1  0  0  0  0  1]
 [25  0  1  0  0  0  0  1  0  1  0  0]
 [20  0  1  0  0  0  0  0  1  0  0  1]
 [37  1  0  0  1  0  0  1  0  1  0  0]
 [24  1  1  0  0  0  1  0  0  0  0  1]
 [26  0  1  0  0  0  0  1  0  0  1  0]
 [33  1  0  1  0  0  1  0  0  1  0  0]
 [25  0  1  0  0  0  0  0  1  0  1  0]
 [27  1  1  0  0  0  1  0  0  1  0  0]
 [20  1  1  0  0  0  0  0  1  1  0  0]
 [18  0  1  0  0  0  0  1

In [30]:
print(y)

[0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 1 1 0
 0 0 1 1 1 1 1 1 1 0 1 0 1 0 1 0 0 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0 1 1 0 0
 1 0 1 1 1 0]


In [31]:
from sklearn.model_selection import train_test_split
from collections import Counter

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, stratify=y)

print(Counter(y_train).values())
print(Counter(y_test).values())


dict_values([27, 37])
dict_values([7, 9])


In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.62667929, -0.82717019,  1.        , -0.69883624, -0.40451992,
        -0.1796053 , -0.62554324,  1.03175391, -0.55328334,  0.8819171 ,
        -0.52915026, -0.52915026],
       [-0.42099993,  1.20894105,  1.        , -0.69883624, -0.40451992,
        -0.1796053 ,  1.59861051, -0.96922337, -0.55328334, -1.13389342,
        -0.52915026,  1.88982237],
       [-0.21532058, -0.82717019, -1.        ,  1.4309504 , -0.40451992,
        -0.1796053 , -0.62554324,  1.03175391, -0.55328334, -1.13389342,
         1.88982237, -0.52915026],
       [ 2.45851107,  1.20894105,  1.        , -0.69883624, -0.40451992,
        -0.1796053 , -0.62554324,  1.03175391, -0.55328334,  0.8819171 ,
        -0.52915026, -0.52915026],
       [ 0.19603814,  1.20894105, -1.        ,  1.4309504 , -0.40451992,
        -0.1796053 ,  1.59861051, -0.96922337, -0.55328334,  0.8819171 ,
        -0.52915026, -0.52915026],
       [-0.21532058,  1.20894105, -1.        ,  1.4309504 , -0.40451992,
        -0.1796053 , -

#Композиции алгоритмов

In [33]:
from sklearn.model_selection import GridSearchCV

##Бэггинг

In [34]:
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB

In [35]:
%%time
clf = GaussianNB()
bgc = BaggingClassifier(clf)

bagging_parameters = {'n_estimators' : range(10, 50, 10), 'max_features' : range(1,5,1)}
bagging = GridSearchCV(bgc, bagging_parameters)
bagging.fit(X_train, y_train)

CPU times: user 2.86 s, sys: 36.9 ms, total: 2.9 s
Wall time: 2.89 s


In [36]:
bagging.best_params_

{'max_features': 3, 'n_estimators': 30}

In [37]:
y_pred = bagging.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[7 0]
 [8 1]]
              precision    recall  f1-score   support

           0       0.47      1.00      0.64         7
           1       1.00      0.11      0.20         9

    accuracy                           0.50        16
   macro avg       0.73      0.56      0.42        16
weighted avg       0.77      0.50      0.39        16



##Бустинг

In [38]:
from sklearn.ensemble import GradientBoostingClassifier

In [39]:
%%time
gbc = GradientBoostingClassifier()
boosting_parameters = {'n_estimators' : range(5,20,5), 'max_depth' : range(1,8,1)}
boosting = GridSearchCV(gbc, boosting_parameters)
boosting.fit(X_train, y_train)

CPU times: user 918 ms, sys: 8.73 ms, total: 927 ms
Wall time: 933 ms


In [40]:
boosting.best_params_

{'max_depth': 1, 'n_estimators': 10}

In [41]:
y_pred = boosting.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[2 5]
 [0 9]]
              precision    recall  f1-score   support

           0       1.00      0.29      0.44         7
           1       0.64      1.00      0.78         9

    accuracy                           0.69        16
   macro avg       0.82      0.64      0.61        16
weighted avg       0.80      0.69      0.63        16



##Стекинг

In [45]:
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [46]:
knc_parameters = {'n_neighbors': range(1, 10, 1)}

knc = KNeighborsClassifier()
clf_knc = GridSearchCV(knc, knc_parameters)

clf_knc.fit(X_train, y_train)
clf_knc.best_params_

{'n_neighbors': 2}

In [47]:
%%time
estimators = [
('gnb', GaussianNB()),
('knn', KNeighborsClassifier(n_neighbors = 2))]

sc = StackingClassifier(estimators=estimators)
sc.fit(X_train, y_train)
y_pred = sc.predict(X_test)
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[0 7]
 [0 9]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.56      1.00      0.72         9

    accuracy                           0.56        16
   macro avg       0.28      0.50      0.36        16
weighted avg       0.32      0.56      0.40        16

CPU times: user 36.3 ms, sys: 0 ns, total: 36.3 ms
Wall time: 38.5 ms


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Вывод

Алгоритм бустинг показал самую высокую точность.

Алгоритм бэггинг сработал немного хуже.

Стекинг показал самую низкую точность.

В целом, точность алгоритмов довольно низкая из-за небольшой подборки данных.